### ISSUE TITLE
YAML list structure

### ISSUE THREAD

**Issue by bast** [sdruskat/citation-file-format#7]
In the file structure we recommend "exactly one message containing instructions ...".
This is perhaps nit-picking (but it is good to settle this early) but I was a bit surprised by the hyphen which signals that this is a list item. Why not `message: If you use this software, please cite the works below.` instead of the one with hyphen?

Related to this (we can split this up into a separate issue) it could be an idea to collect references to `references`. I.e., instead of:
```
- message: If you use this software, please cite the works below.
- type: software-code
  authors:
    - name: ...
      orcid: ...
- type: ...
  authors:
    - name: ...
      orcid: ...
```
rather:
```
message: If you use this software, please cite the works below.
references:
  - type: software-code
    authors:
      - name: ...
        orcid: ...
  - type: ...
    authors:
      - name: ...
        orcid: ...
```
The latter signals to me more clearly that there is only one message and that the types are actually references.
